--- #webservr setup
- hosts: server2 
  user: test
  sudo: yes
  tasks:
   - name: install httpd package
     yum: name=httpd  state=installed
   - name: verify the status
     service: name=httpd state=started
     register: result
   - debug: var= result
